### ISSUE TITLE
Passing Request object to StringInitializable

### ISSUE THREAD

**Issue by sroebert** [vapor/routing#1]
I was working with type safe routing and found myself needing the `Request` to properly parse path parameter. I was wondering why the `StringInitializable` protocol does not include the `Request` in the `init` method.

Would it be an idea to add this parameter, allowing the `Request` to be used?

In my case I needed the `Request`, because I need the logged in user for determining the parameter.

**Comment by tannernelson** [comment]
I think this would be a great addition. It would break public API, so I'll add to 2.0 milestone.

**Comment by LoganWright** [comment]
@tannernelson I wonder if we could do a default implementation like:

```swift
init(string: String, request: Request) {
    self.init(string: string)
}
```

To avoid breaking public api.

**Comment by tannernelson** [comment]
A protocol with the signature `init(string: String, request: Request)` should be called something like `RouteInitializable`. Calling it `StringInitializable` would be strange. In that case we would need to mess around with type aliases to maintain backward compatibility.

**Comment by LoganWright** [comment]
We've made some changes in the core of this lib that negate this issue, hopefully everything works the way you want 👍
