### ISSUE TITLE
3.0 RC 1: String parameter type does not work

### ISSUE THREAD

**Issue by 4np** [vapor/routing#36]
Using a `String.parameter` does not work.

```swift
router.get("cores", String.parameter, "solar", use: solarController.getSolarForCoreByDeviceID)
```

This seems to be related to [this guard statement](https://github.com/vapor/routing/blob/master/Sources/Routing/ParameterContainer.swift#L65) (also see [this discussion](https://github.com/vapor/vapor/issues/1531) with @0xTim):

```swift
guard current.slug == [UInt8](P.uniqueSlug.utf8) else { ... }
```

### Steps to reproduce

Create a route that takes a string parameter:

```
router.get("cores", String.parameter, "solar", use: solarController.getSolarForCoreByDeviceID)
```

Calling the endpoint (e.g. `{{ url  }}/cores/somestring/solar`) will lead to the following error:

```
[ ERROR ] RoutingError.invalidParameterType: Invalid parameter type. Expected String got [99, 111, 114, 101] (ParameterContainer.swift:69)
```

Setting a breakpoint on the parameter line (`let deviceID = try req.parameter(String.self)`) in the controller's implementation shows that [this guard statement](https://github.com/vapor/routing/blob/master/Sources/Routing/ParameterContainer.swift#L65) fails.

Dumping what `slug` and `uniqueSlug` are:

```
        print("----")
        dump("slug: \(String(bytes: current.slug, encoding: .utf8))")
        dump("unique slug: \(P.uniqueSlug.utf8)")
```

results in the following output when requesting `{{ url  }}/cores/somestring/solar`:

```
----
- "slug: Optional(\"core\")"
- "unique slug: string"
[ ERROR ] RoutingError.invalidParameterType: Invalid parameter type. Expected String got [99, 111, 114, 101] (ParameterContainer.swift:73)
```

**Controller:**
```
import Foundation
import Vapor
import Fluent

final class SolarController {
    func getSolarForCoreByDeviceID(_ req: Request) throws -> Future<SolarInfo> {
//        let deviceID = try req.parameters.next(String.self)
        let deviceID = try req.parameter(String.self)
        print("device id: \(deviceID)")
        
        return Core.query(on: req).filter(\Core.deviceID == deviceID).first().flatMap(to: SolarInfo.self) { (core) -> Future<SolarInfo> in
            guard let core = core else {
                throw Abort(.notFound, reason: "No such core")
            }
            
            let solarInfo = SolarInfo(sunrise: core.sunrise, sunset: core.sunset)
            return Future<SolarInfo>(solarInfo)
        }
    }
}

struct SolarInfo: Content {
    var sunrise: Date
    var sunriseTime: String
    var sunset: Date
    var sunsetTime: String
    
    init(sunrise: Date, sunset: Date) {
        self.sunrise = sunrise
        self.sunset = sunset
        
        let timeFormatter = DateFormatter()
        timeFormatter.locale = Locale(identifier: "nl-NL")
        timeFormatter.dateStyle = .none
        timeFormatter.timeStyle = .short
        
        self.sunriseTime = timeFormatter.string(from: sunrise)
        self.sunsetTime = timeFormatter.string(from: sunset)
    }
}
```

### Expected behavior

I expect a `String.parameter` to not fail when called with a string :)

### Actual behavior

The request fails with:

```
Oops: Invalid parameter type. Expected String got [99, 111, 114, 101]
```

### Environment

* Vapor Framework version: 3.0 RC
* Vapor Toolbox version: n/a
* OS version: High Sierra

**Comment by 4np** [comment]
I think this is caused by the following:

```
    let coreController = CoreController()
    router.get("cores", Core.parameter, use: coreController.getByID)

    // Solar
    let solarController = SolarController()
    router.get("cores", String.parameter, "solar", use: solarController.getSolarForCoreByDeviceID)
```

The first route uses a `Core.parameter` whereas the seconds route uses a `String.parameter`. I would expect the Routing logic to match the requests against all of the configured routes, not the first one it encounters?

**Comment by 0xTim** [comment]
It's a bug, I've tried it with a really simple route as well

**Comment by 4np** [comment]
It looks like this works in `RC 2`, however it looks like a new bug #39 was introduced.
