### ISSUE TITLE
Parameters should be percent escaped

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/routing#64]
In Vapor 2 the following code:
```swift
get("hello", ":id") { req in
            let id = req.parameters["id"]?.string

            var json = JSON()
            try json.set("hello", id)
            return json
        }
```

Would produce the following output:

- GET /hello/abc1234 `{"hello":"abc1234"}`
- GET /hello/abc|1234 `{"hello":"abc|1234"}`
- GET /hello/abc%7C1234 `{"hello":"abc|1234"}`

In Vapor 3 instead:

- GET /hello/abc1234 `{"hello":"abc1234"}`
- GET /hello/abc|1234 `{"hello":"abc%7C1234"}` // Notice that this is automatically encoded by any client before sending
- GET /hello/abc%7C1234 `{"hello":"abc%7C1234"}`

This to me seems like a regression.

The code that was taking care of this can be found on `Router.swift` on tag `2.2.1`.
```swift
public func slugs(for path: [String]) -> Parameters {
        var slugs: [String: Parameters] = [:]
        slugIndexes.forEach { key, index in
            guard let val = path[safe: index]
                .flatMap({ $0.removingPercentEncoding })
                .flatMap({ Parameters.string($0) })
                else { return }

            if let existing = slugs[key] {
                var array = existing.array ?? [existing]
                array.append(val)
                slugs[key] = .array(array)
            } else {
                slugs[key] = val
            }
        }
        return .object(slugs)
    }
```

**Comment by valeriomazzeo** [comment]
I have fixed this in https://github.com/valeriomazzeo/routing/commit/0faeca6231cbe4764d82182ed9e1cc0f5c944a66 but I cannot seem to find a branch of this repository where version 3 is maintained, so I can't open a pull request.

**Comment by tanner0101** [comment]
This will also need to be fixed in Vapor 4, so let's keep that in mind after we merge #65.

**Comment by tanner0101** [comment]
Just to be sure we don't need to escape decode anything besides the _parameters_, I ran a quick test against Express.js.

```js
app.get('/static/baz', (req, res) => res.send('foo bar baz'))
app.get('/dynamic/:baz', (req, res) => res.send(req.params.baz))
```

From the results, it seems that Express at least only percent decodes route params, not path components.

### Static

```http
GET /static/ba%7A HTTP/1.1
Content-Length: 0
```

```http
HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 151
Date: Fri, 22 Feb 2019 23:06:39 GMT
Connection: keep-alive

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /static/ba%7A</pre>
</body>
</html>
```

### Dynamic

```http
GET /dynamic/ba%7A HTTP/1.1
Content-Length: 0
```

```http
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 3
ETag: W/"3-u+lgol6jEdIdQGaek98gA7qbkKI"
Date: Fri, 22 Feb 2019 23:06:27 GMT
Connection: keep-alive

baz
```
